<?php

namespace Estin92\DvlaVes\Support;

use Illuminate\Support\Str;

/**
 * Reference list of vehicle makes the DVLA Vehicle Enquiry Service is known to
 * return in its `make` field, for validating or autocompleting against.
 *
 * This is deliberately NOT a backed enum (unlike FuelType, TaxStatus, etc.):
 *
 *  - The set is open and grows as the DVLA adds manufacturers, so an enum would
 *    need a release for every addition and would reject unseen-but-valid makes.
 *  - The DVLA returns makes with inconsistent casing (e.g. "10Ten", "AC (ELECTRIC)",
 *    "Hero MotoCorp Ltd", "LYNK & CO"); there is no clean mapping to PHP case
 *    identifiers.
 *  - There is no per-make behaviour to attach.
 *
 * VehicleData::$make is therefore a plain ?string. Use this class only to
 * check a value against the known set or to offer a picker. A value absent
 * from MAKES is not necessarily invalid: the DVLA may have added it since this
 * snapshot, supplied by the DVLA (DvlaAPIAccess@dvla.gov.uk) on 2026-06-19 11:46.
 */
final class KnownMake
{
    /**
     * Verbatim DVLA make strings, in DVLA's published order.
     *
     * @var list<string>
     */
    public const MAKES = [
        '10Ten',
        'ABARTH',
        'AC',
        'AC (ELECTRIC)',
        'ACCESS',
        'ACURA',
        'Addax',
        'ADLY',
        'ADRIA',
        'AEBI',
        'AEON',
        'AGCO ALLIS',
        'AGRIFAC',
        'AIE',
        'AION',
        'AIXAM',
        'AJP',
        'AJS',
        'ALBION',
        'ALEXANDER DENNIS',
        'ALFA ROMEO',
        'ALFER',
        'ALKE',
        'ALL WHEEL DRIVE',
        'ALPINE',
        'Antonio Carraro',
        'AODES',
        'APEX',
        'APPLIED SWEEPER',
        'APRILIA',
        'ARIIC',
        'ARIX ROTARY',
        'ARO',
        'ARRIVAL',
        'ARTISAN',
        'ASIA',
        'Askoll',
        'ASQUITH',
        'ASTON MARTIN',
        'ATALA',
        'ATLAS',
        'AUDI',
        'AUSA',
        'AUSTIN',
        'AUSTIN HEALEY',
        'AUSTIN MORRIS',
        'AUTO-TRAIL',
        'AUTOSAN',
        'Avant Tecno',
        'AVANTI',
        'AVELING BARFORD',
        'AVIA',
        'AXR',
        'BABETTA',
        'BAIMO',
        'BAJAJ',
        'BAOTIAN',
        'BARON',
        'BARONI',
        'BAROSSA',
        'BASHAN',
        'BATAVUS',
        'BATTISTINIS',
        'BAVARIA',
        'BCS',
        'BD',
        'BEDFORD',
        'BEELINE',
        'Beemobs',
        'BELARUS',
        'Benda',
        'BENELLI',
        'BENFORD',
        'BENTLEY',
        'BENYE',
        'BETA',
        'BETTER',
        'BILIS',
        'BIMOTA',
        'BITELLI',
        'BLATA',
        'BLAW KNOX',
        'Blitz Motors',
        'Blueshark',
        'Bluroc Motorcycles',
        'BMC',
        'BMW',
        'BOB CAT',
        'BOMAG',
        'BOMBARDIER',
        'BOND',
        'BONSER',
        'BOOM',
        'BOSCHUNG',
        'BOVA',
        'BRA',
        'BRANSON',
        'BREMACH',
        'BRISTOL',
        'BRISTOL (BLMC)',
        'BRIT JEFFREY DIAMOND',
        'BRITISH TRACKSTAR',
        'BRIXTON',
        'BRP',
        'BSA',
        'BTM',
        'BUCHER',
        'BUELL',
        'BUGATTI',
        'Buhler Versatile',
        'BUICK',
        'BULLIT',
        'Bullit Motorcycles',
        'BULTACO',
        'BURSTNER',
        'BYD',
        'BZR',
        'CADILLAC',
        'CAETANO',
        'CAGIVA',
        'Cake',
        'CAN-AM',
        'Caofen',
        'CAPRI',
        'CARADO',
        'CARBODIES',
        'CASAL',
        'CASE',
        'CASE IH',
        'CATERHAM',
        'CATERPILLAR',
        'CCM',
        'CCS',
        'CECTEK',
        'CELCO PROFIL',
        'Cenntro',
        'CFMOTO',
        'CH RACING',
        'CHAMP',
        'CHANG MING',
        'CHANGAN',
        'CHARGE',
        'CHAUSSON',
        'CHERY',
        'CHEVROLET',
        'CHEVROLET GMC',
        'CHITUMA',
        'CHONGQING',
        'CHRYSLER',
        'CHUANL',
        'CHUNLAN',
        'CI MOTORHOME',
        'CITROEN',
        'CKR',
        'CLAAS',
        'CLARK',
        'CLASSIC CUSTOM',
        'CLASSIC REPLICAS',
        'CLAYTON',
        'Club Car Urban',
        'COLEMAN MILNE',
        'COLT',
        'COMBILIFT',
        'COMMER',
        'COOPOP',
        'CORVETTE',
        'CORVUS',
        'COSSACK',
        'COUNTY COMM CARS',
        'COVENTRY CLIMAX',
        'CPI',
        'Cramer',
        'CROMPTON (LEYLAND)',
        'CSR',
        'CTM',
        'CUPRA',
        'CZ',
        'DACIA',
        'DAELIM',
        'DAEWOO',
        'DAF',
        'DAF TRUCKS',
        'DAIFO',
        'DAIHATSU',
        'DAIMLER',
        'DAJIANG',
        'DATSUN',
        'DAVID BROWN',
        'DAYANG',
        'Dayi Motor',
        'DAYUN',
        'DE TOMASO',
        'DEMM',
        'DENNIS',
        'DENNIS FIRE',
        'DENZA',
        'DERBI',
        'DETHLEFFS',
        'DEUTZ FAHR',
        'DEWULF',
        'DFSK',
        'DI BLASI',
        'DIECI',
        'Dietz Power',
        'DINLI',
        'DIRT PRO',
        'DODGE',
        'DOOHAN',
        'DOUGLAS',
        'DRAC',
        'DRIVE DEVILBISS',
        'DS',
        'DUCATI',
        'DUKAR',
        'DUPLE',
        'E-Max',
        'EAGLE',
        'EASY RIDER',
        'EBRO',
        'ECO',
        'ECO NECO',
        'ECOOTER',
        'Efun',
        'EGHOLM',
        'EGO',
        'ELECTRA TRUCKS',
        'ELECTRIC MOBILITY',
        'Electric Motion',
        'ELECTRICARS',
        'Energica',
        'ENTERPRISE BUS',
        'EOS',
        'EPC',
        'ERF',
        'ERIDER',
        'ERIK BUELL RACING',
        'Esagono',
        'Eskuta',
        'ETESIA',
        'ETON',
        'ETRUSCO',
        'EUCLID',
        'EUROLINER',
        'EUROTRAC',
        'EVERUN',
        'EVT',
        'EXPLORER',
        'FACTORY',
        'FANTIC MOTOR',
        'FARBOUD',
        'FARIZON',
        'FARMTRAC',
        'FEIYING',
        'Felq',
        'FENDT',
        'FERRARI',
        'FIAT',
        'FISKER',
        'FMC',
        'FODEN',
        'FORD',
        'FORD NEW HOLLAND',
        'FORDSON',
        'FOREST RIVER',
        'FOSTI',
        'FOTON',
        'FREERIDER',
        'FREIGHT ROVER',
        'FSO CARS',
        'FUTONG',
        'FYM',
        'Gaius',
        'GAMAX',
        'GARELLI',
        'Garia',
        'GAS GAS',
        'Gavrix',
        'GEELY',
        'GEHL',
        'GEM',
        'GENERIC',
        'GENESIS',
        'GIANTCO',
        'GILERA',
        'GINETTA',
        'GO-KART',
        'GOES',
        'GOKA',
        'GOODSENSE',
        'GOODYEAR',
        'GORDON MURRAY',
        'GOUPIL',
        'GOVECS',
        'Gowow',
        'GPX',
        'GREAT WALL',
        'GREEVES',
        'GRILLO',
        'GRINNALL',
        'GROVE',
        'GSMOON',
        'GUY',
        'GWM',
        'HAKO',
        'HAMM',
        'HAMMERHEAD',
        'HANWAY',
        'HAOTIAN',
        'HARBILT ELECTRIC',
        'HARDI',
        'HARLEY-DAVIDSON',
        'HARTFORD',
        'HER CHE',
        'Heracles',
        'HERALD',
        'HERALD MOTOR COMPANY',
        'Hero MotoCorp Ltd',
        'HERO PUCH',
        'HERTFORD',
        'HIGER',
        'HILLMAN',
        'HIMO',
        'HINO',
        'HITACHI',
        'HOLDEN',
        'HOLMER EXXACT',
        'HONCHING',
        'HONDA',
        'HONGDOU',
        'HONGYAN',
        'HONGYI',
        'HONLEY',
        'Horwin',
        'Househam',
        'HSUN',
        'HUASHA',
        'HUATIAN',
        'HUMBER',
        'HUMMER',
        'HUONIAO',
        'HURLIMANN',
        'HUSABERG',
        'HUSQVARNA',
        'HY-MAC LTD',
        'HYDREMA',
        'HYMER',
        'HYOSUNG',
        'HYSTER',
        'HYUNDAI',
        'HYUNDAI CONSTRUCTION',
        'HZM',
        'INDCAR',
        'INDIAN MOTORCYCLE',
        'INEOS',
        'INFINITI',
        'INT. HARVESTER',
        'INVACAR',
        'INVACARE',
        'IRIS.BUS',
        'IRIZAR',
        'ISEKI',
        'ISUZU',
        'ISUZU TRUCKS',
        'ITALJET',
        'ITALVEL',
        'ITINEO',
        'IVECO',
        'IVECO FORD',
        'JACOBSEN',
        'JAECOO',
        'JAGUAR',
        'JAMES',
        'JAWA',
        'JAXIN',
        'JCB',
        'JCM',
        'JEEP',
        'JENSEN',
        'JIAJUE',
        'JIALING',
        'JIANSHE',
        'JINCHENG',
        'JINLING',
        'JINLUN',
        'JLG',
        'JM STAR',
        'JOHN ALLEN',
        'JOHN DEERE',
        'JOHNSTON SWEEPERS',
        'JONWAY',
        'JORDAN',
        'JUNGHEINRICH',
        'KAA Speed',
        'KAISAR',
        'KANGDA',
        'KANUNI',
        'Karcher',
        'KARMA',
        'KARRIER',
        'KARSAN',
        'KASEA',
        'KASSBOHRER',
        'KATO',
        'KAWASAKI',
        'KAWASAKI-KL',
        'KAWATA',
        'KAZUMA',
        'KEEN',
        'KEEWAY',
        'KGM',
        'KIA',
        'KIDEN',
        'KINETIC',
        'KING LONG',
        'KINGTON',
        'KINLON',
        'KINROAD',
        'KIOTI',
        'KNAUS',
        'KNIGHT',
        'Kollter',
        'KOMATSU',
        'Kove',
        'KRAMER',
        'KSR MOTO',
        'KTM',
        'KUBOTA',
        'KYMCO',
        'LADA',
        'LAMBORGHINI',
        'LAMBRETTA',
        'LANCIA',
        'LAND ROVER',
        'LANDINI',
        'LANSING LINDE',
        'LAVERDA',
        'LDV',
        'LE VOYAGEUR',
        'LEAPMOTOR',
        'Leeway',
        'LEIKE',
        'LEVC',
        'LEXMOTO',
        'LEXUS',
        'LEYLAND',
        'LHY',
        'LIEBHERR',
        'LIFAN',
        'LIGIER',
        'LIN-HAI',
        'LINCOLN',
        'LINER',
        'LINHAI',
        'LINMAX',
        'LiveWire',
        'LML',
        'LMX BIKES',
        'LOADMAC',
        'LONCIN',
        'LONDON TAXIS INT',
        'LONGJIA',
        'LONSDALE',
        'LOTUS',
        'LUCKY',
        'Lvneng',
        'LVTONG',
        'LYNK & CO',
        'Mac',
        'MAEVING',
        'MAGIRUS DEUTZ',
        'MAGNI',
        'MAHINDRA',
        'MALAGUTI',
        'MAN',
        'MAN/VW',
        'MANET',
        'MANITOU',
        'MARCOS',
        'MARSHALL',
        'Marshell',
        'MARTIN CONQUEST',
        'MASAI',
        'MASERATI',
        'MASH',
        'MASSEY FERGUSON',
        'MATBRO',
        'MATCHLESS',
        'MATHIEU',
        'Maxmov',
        'MAXUS',
        'MAYBACH',
        'MAZDA',
        'MBK',
        'MBP',
        'MCC',
        'MCCORMICK',
        'MCIA',
        'MCLAREN',
        'MCW',
        'MECALAC',
        'Mecatecno',
        'MEGELLI',
        'Melex',
        'MERCEDES BENZ',
        'MERCURY',
        'MERLO',
        'METROCAB',
        'MG',
        'MGB',
        'MGXPOWER',
        'MH MOTORCYCLES',
        'MIA',
        'Micro',
        'MICROCAR',
        'MIG',
        'MINI',
        'MITSUBISHI',
        'MOBILVETTA',
        'MOBYLETTE',
        'MODEC',
        'MODENAS',
        'MOFFETT',
        'MOKE AUTOMIBILI',
        'MONARCH',
        'MONDIAL',
        'MONIKA',
        'MONTESA',
        'Morbidelli',
        'MORGAN',
        'MORINI',
        'MORRIS',
        'MOSKVICH',
        'Motion Healthcare',
        'MOTO AUPA',
        'MOTO GUZZI',
        'MOTO MORINI',
        'MOTO ROMA',
        'MOTO ZETA',
        'MOTOBECANE',
        'MOTOBI',
        'MOTOMEL',
        'MOTOR JIKOV',
        'MOTORHISPANIA',
        'MOTORINI',
        'MOTRON',
        'MOXY',
        'MUIR-HILL',
        'Mullen',
        'MULTIDRIVE',
        'MULTIHOG',
        'MUTT',
        'MV AGUSTA',
        'MZ',
        'Naxeon',
        'NECHT',
        'NECO',
        'NEOPLAN',
        'NEVAL',
        'NEW HOLLAND',
        'NFM',
        'NIESMANN + BISCHOFF',
        'NIPPI',
        'NIPPONIA',
        'NISSAN',
        'NIU',
        'NOBLE',
        'NOOMA',
        'NORTON',
        'NORTON VILLIERS',
        'NSU',
        'NUFFIELD',
        'OLDSMOBILE',
        'OMODA',
        'ONE REHAB',
        'OPEL',
        'OPTARE',
        'ORA',
        'ORION',
        'OSSA',
        'Otto Bock',
        'OUBAO',
        'OVER',
        'OXBO',
        'OXYGEN',
        'PANTHER',
        'Pasquali',
        'PAXSTER',
        'PEGASO',
        'PENTA',
        'PERMOBIL',
        'PERODUA',
        'PEUGEOT',
        'PGO',
        'PHOENIX',
        'PIAGGIO',
        'PILOTE',
        'PINZGAUER',
        'PIONEER',
        'PLA',
        'PLYMOUTH',
        'POCLAIN',
        'POLARIS',
        'POLESTAR',
        'POLSKI-FIAT',
        'PONTIAC',
        'POR',
        'PORSCHE',
        'PORTARO',
        'Powerland',
        'PRAGA',
        'PRIDE',
        'PROTON',
        'PS MOTOR MANET',
        'PUCH',
        'PULSE',
        'QINGQI',
        'QJMOTOR',
        'Quaddy',
        'QUADRO',
        'QUADZILLA',
        'QUANTUM',
        'QWIC',
        'R-VISION',
        'RAIDER',
        'RALEIGH',
        'RANSOME',
        'RAP',
        'RAPIDO',
        'RASCO',
        'RAVO',
        'REDROCK',
        'Reform',
        'REGENT',
        'RELIANT',
        'RENAULT',
        'RENAULT TRUCKS',
        'RENEGADE',
        'REVA',
        'REWACO',
        'RFN',
        'RGNT',
        'Rhino',
        'RHON',
        'RIEJU',
        'RILEY',
        'ROADLESS',
        'ROLLER TEAM',
        'ROLLS ROYCE',
        'ROMA MEDICAL',
        'ROMET MOTORS',
        'ROVER',
        'ROVIGO',
        'ROYAL ALLOY',
        'ROYAL ENFIELD',
        'SAAB',
        'SACHS',
        'SAITING',
        'Sakura',
        'SAME',
        'SAN',
        'SANBEN',
        'SANILI',
        'SANLI',
        'SANTANA',
        'SANY',
        'SANYA',
        'SANYANG',
        'SAO',
        'Sarkcyber',
        'SAVIEM',
        'SAXON',
        'SCAMMELL',
        'SCANIA',
        'SCARAB',
        'SCHAFFER',
        'SCHMIDT',
        'SCOMADI',
        'SCORPA',
        'SCUTUM',
        'SD',
        'SEAT',
        'SECMA',
        'SEDDON/ATKINSON',
        'SEGWAY',
        'Sennebogen',
        'SERES',
        'SETRA',
        'SFM',
        'SFMM',
        'SHE LUNG',
        'SHENKE',
        'SHERCO',
        'SHIBAURA',
        'SHINERAY',
        'SHIRE',
        'SIAMOTO',
        'SILENCE',
        'SIMCA',
        'SIMSON',
        'SINGER',
        'SINNIS',
        'SINSKI',
        'SIROMER',
        'SITCAR',
        'SKODA',
        'SKYGO',
        'SKYJET',
        'SKYTEAM',
        'SKYWELL',
        'SKYWING',
        'SLINGSHOT',
        'SMART',
        'SMC',
        'SMITHS',
        'Solis Tractors',
        'SONIK',
        'SP MOTO',
        'SPY RACING',
        'SSANGYONG',
        'STAR EV',
        'Stark',
        'STEYR',
        'STOTHERT AND PITT',
        'STRATHCARRON',
        'STROMER',
        'STUART TAYLOR',
        'SUBARU',
        'SUKIDA',
        'SUMOTO',
        'SUNBEAM',
        'SUNDIRO',
        'SUNLIGHT',
        'Sunra',
        'SUNRISE MEDICAL',
        'SUPERBYKE',
        'SUPERMOTO',
        'Sur-ron',
        'SURRON',
        'SUZUKI',
        'SUZUKO',
        'SWAP',
        'SWITCH',
        'SWM',
        'SYM',
        'TAFE',
        'TAISHAN',
        'TAIWAN GOLDEN BEE',
        'TAKEUCHI',
        'Talaria',
        'TALBOT',
        'TAM',
        'TAMORETTI',
        'TATA',
        'TAYAKO',
        'TEC',
        'TEMSA',
        'Tenax International',
        'TERBERG',
        'TEREX',
        'TESLA',
        'TEVVA',
        'TGA',
        'TGB',
        'THINK',
        'THUMPSTAR',
        'THWAITES',
        'TIANJIN',
        'TIAYING',
        'Timan',
        'TIPPEN DELTA',
        'TM',
        'TOMOS',
        'TONG YANG',
        'TORO',
        'TORROT',
        'TOYOTA',
        'TRANSBUS INT',
        'Trevor Motorcycles',
        'TRIGANO',
        'TRIUMPH',
        'Tromox',
        'TRS',
        'TVR',
        'TYM',
        'UBCO',
        'Ugbest',
        'Ultraviolette',
        'UM',
        'UMM',
        'UNI CARRIERS',
        'UNIMOG',
        'UNIVERSAL',
        'URAL',
        'URBAN',
        'URSUS',
        'UVM',
        'VALMET',
        'VALPADANA',
        'VALTRA',
        'VAN HOOL',
        'VAN Os MEDICAL',
        'VANDEN PLAS',
        'VAUXHALL',
        'VDL',
        'VDL BOVA',
        'VDL BUS',
        'VECTRIX',
        'VELOCETTE',
        'VELOSOLEX',
        'VENTURI',
        'Verge',
        'VERTEMATI',
        'Vertigo',
        'VESPA (DOUGLAS)',
        'VICON',
        'VICTORY',
        'VMOTO',
        'Voge',
        'VOGELE',
        'VOLGA',
        'VOLKSWAGEN',
        'VOLTA TRUCKS',
        'VOLVO',
        'VONROAD',
        'VOR',
        'VOXAN',
        'VREDO',
        'VULCAN',
        'W+E',
        'WACKER NEUSON',
        'WANGYE',
        'WARRIOR',
        'WARTBURG',
        'WEIDEMANN',
        'WELLS',
        'WESTFIELD',
        'WEV',
        'WHITE KNUCKLE',
        'WHITLOCK BROS',
        'WIBAU',
        'WILDAX',
        'WILLE',
        'WINGATE + ROGERS',
        'WINGET',
        'WIRTGEN',
        'WK BIKES',
        'WLIE',
        'WOLSELEY',
        'WRIGHTBUS',
        'WUYANG',
        'X-SPORT',
        'XEV',
        'XGJAO',
        'XINGYUE',
        'XINLING',
        'XINTIAN',
        'XPENG',
        'Yadea',
        'YALE',
        'YAMAHA',
        'Yamasaki',
        'YAMATI',
        'YAMOTO',
        'YANMAR',
        'YIBEN MEIDOU',
        'YINGANG',
        'YINHUA',
        'YIYING',
        'YUAN',
        'YUTONG',
        'Z Y MOTOR',
        'ZAP',
        'Zapp',
        'ZASTAVA',
        'Zeeho',
        'ZENNCO',
        'ZENOS',
        'ZERO MOTORCYCLES',
        'ZETOR',
        'ZHENHUA',
        'ZHONGNENG',
        'ZNEN',
        'ZONGSHEN',
        'ZONTES',
        'Zurn Harvesting',
    ];

    /**
     * @return list<string>
     */
    public static function all(): array
    {
        return self::MAKES;
    }

    /**
     * Whether the value matches a known DVLA make, compared case-insensitively
     * and ignoring surrounding whitespace. DVLA casing is inconsistent, so an
     * exact match would reject legitimate values differing only in case.
     */
    public static function isKnown(?string $make): bool
    {
        return self::canonical($make) !== null;
    }

    /**
     * The canonical DVLA spelling for the value, matched case-insensitively and
     * ignoring surrounding whitespace, or null when it is not a known make.
     * Use this to normalise input back to DVLA's own casing.
     */
    public static function canonical(?string $make): ?string
    {
        if ($make === null) {
            return null;
        }

        $needle = Str::lower(trim($make));

        if ($needle === '') {
            return null;
        }

        foreach (self::MAKES as $known) {
            if (Str::lower($known) === $needle) {
                return $known;
            }
        }

        return null;
    }
}
